from __future__ import annotations

import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ASK_DIR = REPO_ROOT / "ASK"
TODO_DIR = REPO_ROOT / "Todo"
OUT_DIR = REPO_ROOT / "Knowledge" / "Codex"
OUT_FILE = OUT_DIR / "Codex Index.md"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def obsidian_link(path: Path, heading: str | None = None, label: str | None = None) -> str:
    rel = path.relative_to(REPO_ROOT).as_posix()
    target = rel[:-3] if rel.endswith(".md") else rel
    if heading:
        target = f"{target}#{heading}"
    return f"[[{target}|{label or heading or path.stem}]]"


def extract_ask_codex_blocks() -> list[dict[str, str]]:
    items: list[dict[str, str]] = []
    for path in sorted(ASK_DIR.glob("*.md")):
        if path.name.lower() == "readme.md":
            continue
        text = read_text(path)
        blocks = re.split(r"(?m)^##\s+", text)
        for block in blocks[1:]:
            heading, _, body = block.partition("\n")
            if not re.search(r"\*\*(도구|툴|Tool)\s*:\*\*\s*(.*Codex|.*Claude\+Codex)", body, re.I):
                continue
            question_match = re.search(r"\*\*(질문|Question)\s*:\*\*\s*(.+)", body)
            question = question_match.group(2).strip() if question_match else ""
            date_match = re.match(r"(\d{4}-\d{2}-\d{2})", path.name)
            date = date_match.group(1) if date_match else ""
            items.append(
                {
                    "date": date,
                    "title": heading.strip(),
                    "question": question,
                    "link": obsidian_link(path, heading.strip()),
                }
            )
    return items


def extract_codex_todos() -> list[dict[str, str]]:
    items: list[dict[str, str]] = []
    for path in sorted(TODO_DIR.glob("*.md")):
        text = read_text(path)
        title_match = re.search(r"(?m)^#\s+(.+)", text)
        title = title_match.group(1).strip() if title_match else path.stem
        if "Codex" not in text and "코덱스" not in text:
            continue
        issue_match = re.search(r"Issue\s*#(\d+)|#(\d+)", text)
        issue = next((g for g in issue_match.groups() if g), "") if issue_match else ""
        open_count = len(re.findall(r"(?m)^-\s+\[\s\]\s+", text))
        done_count = len(re.findall(r"(?m)^-\s+\[[xX]\]\s+", text))
        items.append(
            {
                "title": title,
                "link": obsidian_link(path, label=title),
                "issue": issue,
                "open": str(open_count),
                "done": str(done_count),
            }
        )
    return items


def topic_for(text: str) -> str:
    lowered = text.lower()
    if any(word in lowered for word in ["r2", "docs", "문서", "download", "worker"]):
        return "Docs and R2"
    if any(word in lowered for word in ["github", "issue", "project", "git", "pages"]):
        return "GitHub Ops"
    if any(word in lowered for word in ["schedule", "scheduler", "스케줄", "자동화", "cron"]):
        return "Automation"
    return "General"


def build_index() -> str:
    ask_items = extract_ask_codex_blocks()
    todo_items = extract_codex_todos()

    lines = [
        "# Codex Index",
        "",
        "> Generated by `scripts/build_codex_obsidian.py`.",
        "> Source: `ASK/` and `Todo/`",
        "",
        "## Topic Map",
        "",
        "- [[Codex Topics - Automation]]",
        "- [[Codex Topics - Docs and R2]]",
        "- [[Codex Topics - GitHub Ops]]",
        "",
        "## ASK Codex Blocks",
        "",
    ]

    if ask_items:
        current_date = None
        for item in ask_items:
            if item["date"] != current_date:
                current_date = item["date"]
                lines.extend(["", f"### {current_date}", ""])
            label = item["question"] or item["title"]
            topic = topic_for(" ".join([item["title"], item["question"]]))
            lines.append(f"- {item['link']} - {label} `#{topic.replace(' ', '-')}`")
    else:
        lines.append("- No Codex ASK blocks found.")

    lines.extend(["", "## Todo Notes With Codex Context", ""])
    if todo_items:
        for item in todo_items:
            issue = f" Issue #{item['issue']}." if item["issue"] else ""
            lines.append(
                f"- {item['link']} -{issue} open `{item['open']}`, done `{item['done']}`"
            )
    else:
        lines.append("- No Codex Todo notes found.")

    lines.extend(
        [
            "",
            "## Maintenance",
            "",
            "- Open this repository root as the Obsidian vault.",
            "- Regenerate after ASK/Todo updates: `python .\\scripts\\build_codex_obsidian.py`.",
            "- Keep this file generated; put durable synthesis in topic notes.",
            "",
            "#codex #ask #todo",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(build_index(), encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()

