from __future__ import annotations

import re
import shutil
from pathlib import Path
from urllib.parse import quote


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = REPO_ROOT / "Knowledge"
WIKI_DIR = REPO_ROOT / "wiki"
HOME_SOURCE = SOURCE_DIR / "이슈 중심 프로젝트 지식관리.md"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def title_for_source(path: Path) -> str:
    if path == HOME_SOURCE:
        return "Home"
    return path.stem


def slug_for_title(title: str) -> str:
    title = re.sub(r'[\\/:*?"<>|#]+', " ", title)
    title = re.sub(r"\s+", "-", title).strip("-")
    return title or "Untitled"


def escape_md_label(label: str) -> str:
    return label.replace("\\", "\\\\").replace("[", "\\[").replace("]", "\\]")


def repo_blob_link(target: str, label: str) -> str:
    clean = target[:-3] if target.endswith(".md") else target
    if clean.startswith(("ASK/", "Todo/", "Knowledge/")):
        href = "https://github.com/feed-mina/kiba_2026/blob/main/" + quote(clean + ".md", safe="/")
        return f"[{escape_md_label(label)}]({href})"
    return escape_md_label(label)


def collect_pages() -> dict[str, dict[str, str | Path]]:
    pages: dict[str, dict[str, str | Path]] = {}
    used_slugs: set[str] = set()
    for path in sorted(SOURCE_DIR.rglob("*.md")):
        title = title_for_source(path)
        slug = slug_for_title(title)
        base = slug
        n = 2
        while slug in used_slugs:
            slug = f"{base}-{n}"
            n += 1
        used_slugs.add(slug)

        rel_no_ext = path.relative_to(REPO_ROOT).as_posix()[:-3]
        pages[rel_no_ext] = {"path": path, "title": title, "slug": slug}
        pages[path.stem] = {"path": path, "title": title, "slug": slug}
    return pages


def wiki_link_for(target: str, label: str, pages: dict[str, dict[str, str | Path]]) -> str:
    target = target.strip()
    heading = ""
    if "#" in target:
        target, heading = target.split("#", 1)
    target = target[:-3] if target.endswith(".md") else target
    page = pages.get(target) or pages.get(Path(target).stem)
    if not page:
        return repo_blob_link(target, label)
    href = str(page["slug"])
    if heading:
        href += "#" + slug_for_title(heading).lower()
    return f"[{escape_md_label(label)}]({href})"


def convert_obsidian_links(text: str, pages: dict[str, dict[str, str | Path]]) -> str:
    def repl(match: re.Match[str]) -> str:
        raw = match.group(1).strip()
        if "|" in raw:
            target, label = raw.split("|", 1)
        else:
            target, label = raw, Path(raw.split("#", 1)[0]).stem
        return wiki_link_for(target, label.strip(), pages)

    return re.sub(r"\[\[(.*?)\]\]", repl, text)


def add_wiki_header(text: str, source: Path) -> str:
    rel = source.relative_to(REPO_ROOT).as_posix()
    header = [
        "<!--",
        "Generated from Obsidian Knowledge notes.",
        f"Source: {rel}",
        "Do not edit this file directly; edit Knowledge/ and regenerate.",
        "-->",
        "",
    ]
    return "\n".join(header) + text


def export() -> int:
    if not SOURCE_DIR.exists():
        raise SystemExit("Knowledge folder does not exist.")
    pages = collect_pages()
    if WIKI_DIR.exists():
        shutil.rmtree(WIKI_DIR)
    WIKI_DIR.mkdir(parents=True)

    exported = 0
    for key, page in pages.items():
        source = page["path"]
        if not isinstance(source, Path):
            continue
        # Each source appears twice in pages (rel path and stem); export only once.
        if key != source.relative_to(REPO_ROOT).as_posix()[:-3]:
            continue
        text = read_text(source)
        text = convert_obsidian_links(text, pages)
        text = add_wiki_header(text, source)
        write_text(WIKI_DIR / f"{page['slug']}.md", text)
        exported += 1

    sidebar = [
        "# KIBA Wiki",
        "",
        f"- [{escape_md_label('Home')}](Home)",
        f"- [{escape_md_label('프로젝트 현황')}](프로젝트-현황)",
        f"- [{escape_md_label('날짜별 진행 로그')}](날짜별-진행-로그)",
        f"- [{escape_md_label('Docs Index')}](Docs-Index)",
        f"- [{escape_md_label('index.html Board Source')}](index.html-Board-Source)",
        f"- [{escape_md_label('데스크톱-노트북 작업 이어가기')}](데스크톱-노트북-작업-이어가기)",
        f"- [{escape_md_label('Codex Index')}](Codex-Index)",
        f"- [{escape_md_label('Claude Index')}](Claude-Index)",
        "",
        "## Issues",
        "",
    ]
    issue_pages = sorted(
        (page for key, page in pages.items() if key.startswith("Knowledge/Issues/")),
        key=lambda page: str(page["title"]),
    )
    for page in issue_pages:
        sidebar.append(f"- [{escape_md_label(str(page['title']))}]({page['slug']})")
    write_text(WIKI_DIR / "_Sidebar.md", "\n".join(sidebar) + "\n")

    return exported


def main() -> None:
    count = export()
    print(f"Wrote {count} GitHub Wiki page(s) to {WIKI_DIR.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
