#!/usr/bin/env python3
"""Generate seed candidates that link workbook calculation policies to legal articles."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DOMAIN_PATH = REPO_ROOT / "data" / "sample_ver1_cost_db" / "ver2" / "domain_tables.json"
OUT_DIR = REPO_ROOT / "data" / "defense_cost_rule_db"


POLICY_LINK_RULES = {
    "P001": {
        "article_no": "제6조",
        "legal_policy_code": "DEF_COST_COMPONENT_ROLLUP_V1",
        "legal_basis_kind": "primary",
        "required_variables": ["source_cell", "target_component"],
        "notes": "Excel 시트 간 rollup lookup. 원가 구성요소와 총액 구성에 해당.",
    },
    "P002": {
        "article_no": "제23조",
        "legal_policy_code": "DEF_INDIRECT_COST_V1",
        "legal_basis_kind": "primary",
        "required_variables": ["base_amount", "rate_percent"],
        "notes": "제조간접비/간접비율 적용 산식.",
    },
    "P003": {
        "article_no": "제6조",
        "legal_policy_code": "DEF_COST_COMPONENT_SUM_V1",
        "legal_basis_kind": "primary",
        "required_variables": ["component_amounts"],
        "notes": "비목 소계와 총계 집계 산식.",
    },
    "P004": {
        "article_no": "제23조",
        "legal_policy_code": "DEF_INDIRECT_COST_V1",
        "legal_basis_kind": "primary",
        "required_variables": ["base_amount", "rate_percent"],
        "notes": "보험료/간접경비 계열 base * rate 절사 산식.",
    },
    "P005": {
        "article_no": "제23조",
        "legal_policy_code": "DEF_INDIRECT_COST_V1",
        "legal_basis_kind": "primary",
        "required_variables": ["base_amount", "rate_percent"],
        "notes": "재료비+노무비 등 복합 base에 대한 간접비율 적용.",
    },
    "P006": {
        "article_no": "제6조",
        "legal_policy_code": "DEF_MANUFACTURING_COST_SUM_V1",
        "legal_basis_kind": "primary",
        "required_variables": ["material_total", "labor_total", "expense_total"],
        "notes": "제조원가 구성 합산.",
    },
    "P007": {
        "article_no": "제24조",
        "legal_policy_code": "DEF_GENERAL_ADMIN_V1",
        "legal_basis_kind": "primary",
        "required_variables": ["manufacturing_cost_base", "general_admin_rate"],
        "notes": "일반관리비 산식. 방산 규칙에서는 관급재료비 포함 정책 분기가 필요.",
    },
    "P008": {
        "article_no": "제26조",
        "legal_policy_code": "DEF_PROFIT_V1",
        "legal_basis_kind": "primary",
        "required_variables": ["profit_base_amount", "profit_rate"],
        "notes": "이윤 산식. sample ver2는 15% 고정 예시.",
    },
}


DISPLAY_OR_TAX_POLICIES = {
    "P009": "부가가치세 산식. 방산원가 규칙 본문 계산정책보다는 세금/결과 표시 정책으로 분리.",
    "P010": "천단위 절사 표시 산식. 원가계산 법령 조문보다 산출서 표시 정책.",
    "P011": "결과표 합계 표시 산식. 원가계산 법령 조문보다 산출서 표시 정책.",
}


def sql_quote(value: Any) -> str:
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def load_policies() -> list[dict[str, Any]]:
    tables = json.loads(DOMAIN_PATH.read_text(encoding="utf-8"))
    return tables.get("calculation_policy", {}).get("rows", [])


def build_links(policies: list[dict[str, Any]]) -> dict[str, Any]:
    links: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []
    for policy in policies:
        code = policy["policy_code"]
        rule = POLICY_LINK_RULES.get(code)
        if rule:
            links.append(
                {
                    "source_policy_code": code,
                    "article_no": rule["article_no"],
                    "legal_policy_code": rule["legal_policy_code"],
                    "legal_basis_kind": rule["legal_basis_kind"],
                    "formula_kind": policy["formula_kind"],
                    "excel_formula_template": policy["excel_formula_template"],
                    "example": policy["example"],
                    "occurrence": policy["occurrence"],
                    "required_variables": rule["required_variables"],
                    "required_evidence": ["source_workbook_cell", "legal_article"],
                    "notes": rule["notes"],
                }
            )
        else:
            skipped.append(
                {
                    "source_policy_code": code,
                    "formula_kind": policy["formula_kind"],
                    "excel_formula_template": policy["excel_formula_template"],
                    "example": policy["example"],
                    "occurrence": policy["occurrence"],
                    "reason": DISPLAY_OR_TAX_POLICIES.get(code, "조문 링크 후보 미분류"),
                }
            )
    return {"links": links, "skipped": skipped}


def render_sql(seed: dict[str, Any]) -> str:
    lines = [
        "-- Generated by scripts/generate_defense_rule_policy_links.py",
        "-- Links existing sample_ver1_cost_db/ver2 calculation policies to defense cost rule articles.",
        "",
    ]
    for row in seed["links"]:
        variables_json = json.dumps(row["required_variables"], ensure_ascii=False)
        evidence_json = json.dumps(row["required_evidence"], ensure_ascii=False)
        variable_rules = {
            "source_policy_code": row["source_policy_code"],
            "excel_formula_template": row["excel_formula_template"],
            "example": row["example"],
            "occurrence": row["occurrence"],
        }
        variable_rules_json = json.dumps(variable_rules, ensure_ascii=False)
        lines.append(
            "insert into legal_calculation_policy_link ("
            "id, article_id, policy_id, policy_code, legal_basis_kind, "
            "required_variables, required_evidence, variable_rules, notes"
            ") select "
            "gen_random_uuid(), "
            "la.id, "
            "cp.id, "
            f"{sql_quote(row['legal_policy_code'])}, "
            f"{sql_quote(row['legal_basis_kind'])}, "
            f"{sql_quote(variables_json)}::jsonb, "
            f"{sql_quote(evidence_json)}::jsonb, "
            f"{sql_quote(variable_rules_json)}::jsonb, "
            f"{sql_quote(row['notes'])} "
            "from legal_article la "
            "left join calculation_policy cp "
            f"on cp.policy_code = {sql_quote(row['source_policy_code'])} "
            f"where la.article_no = {sql_quote(row['article_no'])} "
            f"and la.is_supplementary = false "
            "on conflict (article_id, policy_code, legal_basis_kind) do nothing;"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    seed = build_links(load_policies())
    (OUT_DIR / "policy_article_links.json").write_text(
        json.dumps(seed, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (OUT_DIR / "policy_article_links.sql").write_text(render_sql(seed), encoding="utf-8")
    print(f"links={len(seed['links'])} skipped={len(seed['skipped'])}")
    print(f"wrote {OUT_DIR / 'policy_article_links.json'}")
    print(f"wrote {OUT_DIR / 'policy_article_links.sql'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
